services:
  postgres:
    image: 'postgres:17.2-alpine3.21'
    environment:
      - 'POSTGRES_DB=streaming'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5000:5432'
