services:
  postgres-streaming:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=streaming'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
